Fixed Scripts to comply with POSIX

diff --git a/gamelaucher b/gamelaucher
--- a/gamelaucher
+++ b/gamelaucher
@@ -1,12 +1,26 @@
 #!/bin/bash
-[ -n "$(printf "%s" $1 | grep -o -i -E '^help|^--help|^-h|^h' )" ] && printf "%s\n" "gameslist [add] <Game Name> <Game Launch Command>" && exit
-gamelistfile="~/.cache/gamelaucher-bash/gameslist"
-gamesList=$(cat ~/.cache/gamelaucher-bash/gameslist)
-[ -n "$(printf "%s" $1 | grep -o -i -E '^add|^--add|^insert|^--insert' )" -a -n "$2" -a -n "$3" ] && printf "Added:\n\tName: %s\n\tCommand: %s\n" "$2" "$3" && printf "%s;%s\n" "$2" "$3" >> ~/.cache/gamelaucher-bash/gameslist && exit
-[ -n "$(printf "%s" $1 | grep -o -i -E '^del|^delete|^--delete|^rm|^--remove|^remove' )" -a -n "$2" ] && printf "%s\n" "$gamesList" | awk -F ";" -v mth=$2 '$1 != mth {print $0}' > $gamelistfile && exit
-gameSelected=$(cat ~/.cache/gamelaucher-bash/gameslist  | awk -F ";" '{print $1}' | dmenu -p 'Games: ')
+gamelistfile="$HOME/.cache/gamelaucher-bash/gameslist"
+gamesList=$(cat "$gamelistfile")
+case "$1" in
+    '^help|^--help|^-h|^h')
+        printf "%s\n" "gameslist [add] <Game Name> <Game Launch Command>"
+        exit
+        ;;
+    '^add|^--add|^insert|^--insert')
+        [ -z "$2" ] || [ -z "$3" ] && printf "%s\n" "Missing Alias or Command." && exit 1
+        printf "Added:\n\tName: %s\n\tCommand: %s\n" "$2" "$3" && printf "%s;%s\n" "$2" "$3" >> "$gamelistfile" 
+        exit
+        ;;
+
+    '^del|^delete|^--delete|^rm|^--remove|^remove')
+        [ -z "$2" ] && printf "Missing alias to remove." && exit 1
+        printf "%s\n" "$gamesList" | awk -F ";" -v mth="$2" '$1 != mth {print $0}' > "$gamelistfile"
+        exit
+        ;;
+esac
+gameSelected=$(awk -F ";" '{print $1}' < "$gamelistfile" | dmenu -p 'Games: ')
 [ -z "$gameSelected" ] && exit
-gameCommand=$(cat ~/.cache/gamelaucher-bash/gameslist | awk -F ";" -v mth="$gameSelected" '$1 == mth {$1="";print $0}')
+gameCommand=$(awk -F ";" -v mth="$gameSelected" '$1 == mth {$1="";print $0}' < "$gamelistfile")
 printf "Game: %s\nCommand: %s\n" "$gameSelected" "$gameCommand"
 printf "%s\n" "$gameCommand" | xargs -I% bash -c %
 #${SHELL:-"/bin/sh"} -c ${gameLaunchCommand}
diff --git a/gif-compress b/gif-compress
--- a/gif-compress
+++ b/gif-compress
@@ -1,18 +1,18 @@
 #!/bin/bash
-[ -z "$1" ] && printf "Missing input files\n" && exit 
-[ "$1" == "-h" -o "$1" == "--help" ] && printf "$0 <Input File> [OPTIONS] <Output File>\n\t-s\tset the size of the gif\n\t-c\tset the amount of color\n\t-f\tset the fuzzyness" && exit
+[ -z "$1" ] && printf "Missing input files\n" && exit 1
+[ "$1" == "-h" ] || [ "$1" == "--help" ] && printf "%s\n\t%s\t%s\n\t%s\t%s\n\t%s\t%s\n" "$0 <Input File> [OPTIONS] <Output File>" "-s" "set the size of the gif" "-c" "set the amount of color" "-f" "set the fuzzyness" && exit 0
 
-IFile=$1
+IFile="$1"
 shift
 #scaleinput="-scale 400x400"
 # colors="--colors 128"
 # fuzz="-fuzz 15%"
 while [ $# -gt 1 ];
 do
-    case $1 in
+    case "$1" in
         -s)
             shift
-            if [ -z "$(printf "%s" "$1" | grep "x")" ]; then
+            if ! printf "%s" "$1" | grep -q "x"; then
                 scaleinput="-scale $1x$1"
                 extentinput="-extent $1x$1"
             else
@@ -23,17 +23,17 @@ do
             ;;
         -c)
             shift
-            colors="--colors $1"
+            colors=" --colors $1"
             shift
             ;;
         -f)
             shift
-            fuzz="-fuzz $1"
+            fuzz=" -fuzz $1"
             shift
             ;;
         -l)
             shift
-            lossy="--lossy=$1"
+            lossy=" --lossy=$1"
             shift
             ;;
         -loop)
@@ -42,7 +42,7 @@ do
             ;;
         --repeat)
             [ -z "$1" ] && rTimes=2 || rTimes=$1
-            repeat="-colesce -duplicate${rTimes},1--1 -loop 0"
+            repeat=" -colesce -duplicate${rTimes},1--1 -loop 0"
             ;;
         *)
             shift
@@ -50,12 +50,12 @@ do
     esac
 done
 
-[ -z "$1" ] && printf "Missing input files\n" && exit 
+[ -z "$1" ] && printf "Missing input files\n" && exit  1
 
 printf "%s\n" "magick $IFile -verbose -coalesce $loop $repeat $scaleinput -gravity center -background \"rgba(0,0,0,0)\" -compose copy $extentinput $fuzz +dither -dispose previous $loop temp-output.gif"
-magick $IFile -verbose -coalesce $scaleinput -gravity center -background "rgba(0,0,0,0)" -compose copy $extentinput $fuzz +dither -dispose previous $loop temp-output.gif
+magick "$IFile" -verbose -coalesce $scaleinput -gravity center -background "rgba(0,0,0,0)" -compose copy $extentinput $fuzz +dither -dispose previous $loop temp-output.gif
 
 printf "%s\n" "gifsicle -O3 $lossy $colors temp-output.gif -o $1"
-gifsicle -O3 $lossy $colors temp-output.gif -o $1
+gifsicle -O3 $lossy $colors temp-output.gif -o "$1"
 
 rm temp-output.gif
diff --git a/soundpost b/soundpost
--- a/soundpost
+++ b/soundpost
@@ -1,13 +1,14 @@
 #!/bin/bash
 [ -z "$1" ] && printf "Missing file\n" 2>&1 && exit
 sound=$(printf "%s" "$1" | grep -o "\[sound=.*\]" | sed -e 's/\[sound=//g' -e 's/\]//g' -e 's/%3A/\:/g' -e 's/%2F/\//g')
-if [ -z "$(printf "%s" \"$sound\" | grep -E 'https|http')" -a -n "$sound" ]; then
+if ! printf "%s\n" "$sound" | grep -Eq 'https|http' && [ -n "$sound" ]; then
     soundlink=" -i https://$sound"
-    map="-map 0:v:0 -map 1:a:0"
 elif [ -n "$sound" ]; then
     soundlink=" -i $sound"
+else
+    printf "%s\n" "Sound Not Found!" 2>&1 && exit 1 
 fi
-ffmpeg -ignore_loop 0 -i "$1" $soundlink -pix_fmt yuv420p -deinterlace -vf "scale=iw/2:-2"  -vsync 1 -max_interleave_delta 0 -vcodec libx264 -r 29.970 -threads 0 -b:v: 1024k -bufsize 1216k -maxrate 1280k -preset medium -profile:v main -tune film -g 60 -x264opts no-scenecut -acodec aac -b:a 192k -ac 2 -ar 44100 -af "aresample=async=1:min_hard_comp=0.100000:first_pts=0"  $map -f matroska -y pipe:1 | ffplay - -framedrop -infbuf 
+ffmpeg -ignore_loop 0 -i "$1" "$soundlink" -pix_fmt yuv420p -deinterlace -vf "scale=iw/2:-2"  -vsync 1 -max_interleave_delta 0 -vcodec libx264 -r 29.970 -threads 0 -b:v: 1024k -bufsize 1216k -maxrate 1280k -preset medium -profile:v main -tune film -g 60 -x264opts no-scenecut -acodec aac -b:a 192k -ac 2 -ar 44100 -af "aresample=async=1:min_hard_comp=0.100000:first_pts=0"  -map 0:v:0 -map 1:a:0 -f matroska -y pipe:1 | ffplay - -framedrop -infbuf 
 # mpv "$1" --audio-file="$soundlink" --loop-file=inf --loop=yes
 #ffmpeg -probesize 20M -i "$1" $soundlink  -vf "scale=iw/2:-2" -max_interleave_delta 0 -vsync 1 -c:v libx264  -tune film -threads 0 -preset ultrafast $map  -fflags nobuffer -r 29.970 -g 60 -movflags +faststart -c:a aac -f matroska pipe:1 | ffplay - -framedrop -infbuf 
 # -vf "scale=640:360"
