Rewrote gdrive-dl into more simpler code

diff --git a/gdrive-dl b/gdrive-dl
--- a/gdrive-dl
+++ b/gdrive-dl
@@ -1,8 +1,14 @@
 #!/bin/bash
-[ -z "$1"  ] && printf "%s\n" "Missing google drive link" >&2 && exit 1
+# check if the input is valid
+# * Must not be empty
+[ -z "$1" ] && printf "%s\n" "Missing google drive link" >&2 && exit 1
+# * Must have https://drive.google.com at the start and must have "file" or drive after it
+grep -viq '^https://drive.google.com/file\|drive' <<< "$1" && printf "%s\n" "Invalid google drive link" && exit 1
 
+# Set array seperator
 oldIFS=$IFS
 IFS=$'\n'
+# Get info from drive
 rawDrive=$(curl -L -s "$1")
 driveName=$(printf "%s\n" "$rawDrive" | grep -Eoi "title>.+ - " | sed -e 's/^title>//g' -e 's/ - $//g')
 if printf '%s\n' "$rawDrive" | grep -ioq 'drive.google.com/file'; then
@@ -16,100 +22,54 @@ IFS=$oldIFS
 
 fileNum=${#fileLinks[@]}
 
+# Index drive files
 fileSequence=$(seq 0 $(("$fileNum" - 1)))
 
+# Drive Title Header
 printf "====================\n\n%s\n\n====================\n\n" "Drive Title: $driveName"
 
+# List all the files in the google drive
 for ((FN=0; FN < "$fileNum"; FN++)); do
     printf "%s\n#%-5sFilename: %s\n\tFileID: %s\n%s\n\n" "--------------------" "${FN}:" "${fileNames[$FN]}" "${fileLinks[$FN]}" "--------------------"
 done
 
-printf "%s\n" 'To exlcude files (eg: "-10", "-1 -3 -7", "-5-14")'
-printf "%s\n" 'To include files (eg: "10", "1 3 7", "5-14")'
+printf "%s\n" 'To exlcude files (eg: "-10", "-1 -3 -7")'
+printf "%s\n" 'To include files (eg: "10", "1 3 7")'
 printf "%s\n" 'Put in nothing to include everything'
 
-while true; do
-    printf "%s" '==> ' && read -r fileOptions
-    [ -z "$fileOptions" ] || printf "%s\n" "$fileOptions" | grep -Eoq '^(-*)[0-9]+(-[0-9]+){0,1}( [0-9]+)*$' || break
-    printf "Input is not valid\n"
-done
 
-
-
-if printf '%s\n' "$fileOptions" | grep -Eoi '(-*)[0-9]+-[0-9]+$'; then
+# Ask the user for files to include or exclude
+printf "%s" '==> ' && read -r -a fileOptions
+if [ -z "$fileOptions" ]; then
     downloadOption=0
-elif printf '%s\n' "$fileOptions" | grep -Eo '^(-*)[0-9]+( (-*)[0-9]+)+'; then
+    choosenLink=(${fileLinks[@]})
+    choosenName=(${fileNames[@]})
+elif printf '%s\n' "$fileOptions" | grep -Eoq '^[0-9]+( [0-9]+)*$'; then
     downloadOption=1
-else
+    for elem in ${fileOptions[@]}; do
+        [ "$elem" -ge "$fileNum" ] && continue
+        choosenLink+=("${fileLinks[$elem]}")
+        choosenName+=("${fileNames[$elem]}")
+    done
+elif printf '%s\n' "$fileOptions" | grep -Eoq '^-[0-9]+( -[0-9]+)*$'; then
     downloadOption=2
+    choosenLink=(${fileLinks[@]})
+    choosenName=(${fileNames[@]})
+    for elem in ${fileOptions[@]}; do
+        posElem=$(( elem * -1 ))
+        [ $posElem -ge $fileNum ] && continue
+        choosenLink=("${choosenLink[@]/${fileLinks[$posElem]}}")
+        choosenName=("${choosenName[@]/${fileNames[$posElem]}}")
+    done
+else
+    printf "Invalid Input!\n" 
+    exit 1;
 fi
 
-
-function driveDownload {
-    fileName="${fileNames[$1]}"
-    fileLink="https://drive.google.com/uc?id=${fileLinks[$1]}&authuser=0&export=download&confirm=t"
-    printf "Filename: %s\n" "$fileName"
-    printf "Link: %s\n" "$fileLink"
-    curl -L -o "$fileName" "$fileLink"
-}
-
-case "$downloadOption" in
-    0)
-        printf '%s\n' "1st Option"
-        oldIFS=$IFS
-        IFS=$'-'
-        splitRange=( "$(printf '%s\n' """$fileOptions""" | sed 's/^-//g')" )
-        if [ "${splitRange[0]}" -lt "${splitRange[1]}" ]; then
-            minRange=${splitRange[0]}
-            maxRange=${splitRange[1]}
-        else
-            minRange=${splitRange[1]}
-            maxRange=${splitRange[0]}
-        fi
-        IFS=$oldIFS
-
-        printf "N: %s\nX:%s\n" "$minRange" "$maxRange"
-
-        if ! printf "%s\n" "$fileOptions" | grep -o '^-'; then
-            finalRange=$(printf '%s\n' "$fileSequence" | sed 's/'"^[$minRange-$maxRange]"'//g')
-        else
-            finalRange=$(printf '%s\n' "$fileSequence" | grep -Eo "(^[$minRange-$maxRange])$")
-        fi
-        printf "%s\n" "$finalRange"
-
-
-        for downloadNum in $finalRange; do
-            driveDownload "$downloadNum"
-        done
-
-        ;;
-    1)
-        printf '%s\n' "2nd Option"
-        if ! printf "%s\n" "$fileOptions" | grep -o '^-'; then
-            positiveValues="$(printf "%s\n" "$fileOptions" | grep -o '[0-9]*')"
-            finalRange=( "$(printf '%s\n' "$fileSequence" | grep -Ev "$positiveValues")" )
-        else
-            finalRange="$fileOptions"
-        fi
-
-        for downloadNum in $finalRange; do
-            driveDownload "$downloadNum"
-        done
-        ;;
-    2)
-        printf '%s\n' "3rd Option"
-        if ! printf "%s\n" "$fileOptions" | grep -o '^-'; then
-            finalRange=$(printf "%s\n" "$fileSequence" | sed 's/'"$($fileOptions / -1 )"'//g')
-        elif [ -z "$fileOptions" ]; then
-            finalRange="$fileSequence"
-        else
-            finalRange="$fileOptions"
-        fi
-
-        printf '%s\n' "$finalRange"
-
-        for downloadNum in $finalRange; do
-            driveDownload "$downloadNum"
-        done
-        ;;
-esac
+for ((item=0; item<${#choosenLink[@]}; item++)); do
+    fileLink="https://drive.google.com/uc?id=${choosenLink[$item]}&authuser=0&export=download&confirm=t"
+    printf "Filename: %s\n" "${choosenName[$item]}"
+    printf "Link: %s\n" "${choosenLink[$item]}"
+    #curl -L --fail -o "${choosenName[$item]}" "$fileLink"
+    wget -O "${choosenName[$item]}" "$fileLink"
+done
